### ISSUE TITLE
Unhandled Exception upon startup in newest version 

### ISSUE THREAD

**Issue by Titangamer2327** [HDoujinDownloader/HDoujin-Downloader#14]
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.TypeInitializationException: The type initializer for '⁮‏‏‫‪‌‌‫⁭​​⁮‎​⁬⁯⁭‫⁫‎​‏‬​⁯‌⁪‏‪‌‭‭​‪‌​‮‬‭⁯‮' threw an exception. ---> System.IO.FileNotFoundException: Could not load file or assembly 'WebDriver, Version=3.141.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
   at ⁮‏‏‫‪‌‌‫⁭​​⁮‎​⁬⁯⁭‫⁫‎​‏‬​⁯‌⁪‏‪‌‭‭​‪‌​‮‬‭⁯‮..cctor()
   --- End of inner exception stack trace ---
   at )vYnqd?'HHa<-c{LVnn=yQbJ!.‫‫‍‪⁮⁯⁭‌⁭⁬⁫‌‫⁯‫⁪‮⁫‪⁬‪‎‌‭⁭‮⁮‌‮‪⁫‎‭⁫⁫​‮‮‏⁯‮(Object , EventArgs )
   at System.Windows.Forms.Form.OnDeactivate(EventArgs e)
   at System.Windows.Forms.Form.set_Active(Boolean value)
   at System.Windows.Forms.Form.WmActivate(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4300.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
HDoujin Downloader
    Assembly Version: 2021.2.11.0
    Win32 Version: 2021.2.11.0
    CodeBase: file:///C:/Users/awolf/Downloads/52%2065%2067%2069%2073%2074%2072%2079/41/31/21/Hentai/image/New%20folder%20(6)/HDoujin.Downloader.exe
----------------------------------------
UxlfLRTISjfmwRltbWRXZwjcafSi
    Assembly Version: 0.0.0.0
    Win32 Version: 2021.2.11.0
    CodeBase: file:///C:/Users/awolf/Downloads/52%2065%2067%2069%2073%2074%2072%2079/41/31/21/Hentai/image/New%20folder%20(6)/HDoujin.Downloader.exe
----------------------------------------
Microsoft.VisualBasic
    Assembly Version: 10.0.0.0
    Win32 Version: 14.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualBasic/v4.0_10.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualBasic.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4300.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4320.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4270.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Runtime.Remoting
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Remoting/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Remoting.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by HDoujinDownloader** [comment]
It looks like this error shows up when you run the program as a standalone executable without any of the dependencies included in the `lib` directory. In particular, `WebDriver.dll` is missing. 

While this shouldn't occur and I'll aim to get it fixed for the next update, I don't recommend running it without its dependencies anyway, because `MoonSharp.Interpreter.dll` is required for Lua module support, and a lot of site modules are now implemented in Lua.

Download the ZIP archive [here](https://github.com/HDoujinDownloader/HDoujin-Downloader/releases/download/v2021.2.11.0/HDoujin.Downloader-2021.2.11.0-win.zip) (which contains the missing dependencies), extract it somewhere, and then try running `HDoujin Downloader.exe` from there. That should solve the problem.

**Comment by Titangamer2327** [comment]
oh okay sorry, ignore my most recent one then...I just now saw this
