### ISSUE TITLE
Problem downloading image form hentai-foundry

### ISSUE THREAD

**Issue by user3430534** [HDoujinDownloader/HDoujin-Downloader#16]
Hello there

I'm having a problem downloading one image from https://www.hentai-foundry.com
Here's a direct link to [problem page (NSFW)](https://www.hentai-foundry.com/pictures/user/cherry-gig/886166/Bad-girls-like-it-Rough.)
The image and the page is accessible. 

And here's the log output that is generated when i press download
```
08:52:31    hdoujin down[i] Locale: en-US
08:52:31    hdoujin down[i] Path: Programs\HDoujin Downloader\HDoujin Downloader.exe
08:52:31    hdoujin down[i] Working Directory: Programs\HDoujin Downloader
08:52:31    hdoujin down[i] Timestamp: 2/22/2021 8:40:40 AM
08:52:31    hdoujin down[i] Product Version: 2021.2.11
08:52:31    hdoujin down[i] Available Security Protocols: SSL 3.0, TLS 1.0, TLS 1.1, TLS 1.2, TLS 1.3
08:52:31    hdoujin down[i] Standalone: False
08:52:31    hdoujin down[i] Repositories: Official Lua Repository, Internal
08:52:31    hdoujin down[i] Theme: Default
08:52:31    http        [x] Exception was thrown when accessing http://www.hentai-foundry.com/pictures/user/cherry-gig/886166/Bad-girls-like-it-Rough.: System.Net.WebException: Too many automatic redirections were attempted.
   at System.Net.HttpWebRequest.GetResponse()
   at ‍‭‮⁫‮⁭⁫⁮⁮‭‮‪⁭⁭‌⁭​⁪‫‏‪⁪‍‪​⁪‪‪⁭⁫⁮‏‪⁯⁪‎⁭⁬‫⁯‮.‎⁪​‌⁯‌⁭⁯‮‪​‬‬‌⁪⁭⁪⁪‪‮⁮‬‮‪⁫⁬⁮⁬⁪⁫‪⁪⁯‮⁫⁯‫⁪‏‍‮(String , CookieContainer , String[] , String , ‮⁯‌⁪⁪⁫‪‏⁬​‏‪‫‭‏⁪‍‮‬⁭‫‪⁮‪⁫‌‭‌‍‭‌‫‬‪⁪‫‎⁪​⁮‮ , String[] )
08:52:31    download    [!] An error occurred while downloading http://www.hentai-foundry.com/pictures/user/cherry-gig/886166/Bad-girls-like-it-Rough.: System.Net.WebException: Too many automatic redirections were attempted.
   at ‍‭‮⁫‮⁭⁫⁮⁮‭‮‪⁭⁭‌⁭​⁪‫‏‪⁪‍‪​⁪‪‪⁭⁫⁮‏‪⁯⁪‎⁭⁬‫⁯‮.‎⁪​‌⁯‌⁭⁯‮‪​‬‬‌⁪⁭⁪⁪‪‮⁮‬‮‪⁫⁬⁮⁬⁪⁫‪⁪⁯‮⁫⁯‫⁪‏‍‮(String , CookieContainer , String[] , String , ‮⁯‌⁪⁪⁫‪‏⁬​‏‪‫‭‏⁪‍‮‬⁭‫‪⁮‪⁫‌‭‌‍‭‌‫‬‪⁪‫‎⁪​⁮‮ , String[] )
   at ‌‭​‎⁭‭⁮‏⁪‮‌‎‌‪‏⁮⁪⁭‮⁪⁯⁭⁫‌⁬‬⁬‮‫‏⁭⁮‬‮⁬‭⁬‫‍⁫‮.‪⁭​⁪‌⁮‭⁮‭⁬‮⁮‬⁮⁪‮⁪⁮‫‮⁯⁭‬⁮⁬‬‭⁯⁬⁪⁭‏⁬​‫‭⁪⁬⁮‬‮(String& )
   at ⁯⁫​⁮⁯​‏⁭⁮⁯‍‫‏‮​‪‮‬‫‬‏⁫‍⁭‏​⁫‎‎‎⁫‎⁬‌‍‫⁮‭⁮⁪‮.‎⁯‬⁪⁯⁮‪⁮‎​⁫‎‪‫⁯‫‎‪‮‬⁫‎⁪​‮‭⁭‫‌‮⁭⁬‫‍⁪‪‬‮‫‎‮(‫‏​‫⁫‮⁪⁯‍‭⁫‌⁪​​‏‬⁪‮​⁭⁭⁮⁪⁯⁫⁭⁯‎⁭‪‏‏‍⁫‭⁫⁬⁮⁪‮ , String , ‌⁫​‭‏‎‮‌⁮⁫​‪‭⁮‪⁭‮⁮⁯‫⁫⁫‏‌⁮⁬​‪⁭⁯‌‎‭⁭‍‪⁭‎⁮⁬‮ )
08:52:31    http        [x] Exception was thrown when accessing http://www.hentai-foundry.com/pictures/user/cherry-gig/886166/Bad-girls-like-it-Rough.: System.Net.WebException: Too many automatic redirections were attempted.
   at System.Net.HttpWebRequest.GetResponse()
   at ‍‭‮⁫‮⁭⁫⁮⁮‭‮‪⁭⁭‌⁭​⁪‫‏‪⁪‍‪​⁪‪‪⁭⁫⁮‏‪⁯⁪‎⁭⁬‫⁯‮.‎⁪​‌⁯‌⁭⁯‮‪​‬‬‌⁪⁭⁪⁪‪‮⁮‬‮‪⁫⁬⁮⁬⁪⁫‪⁪⁯‮⁫⁯‫⁪‏‍‮(String , CookieContainer , String[] , String , ‮⁯‌⁪⁪⁫‪‏⁬​‏‪‫‭‏⁪‍‮‬⁭‫‪⁮‪⁫‌‭‌‍‭‌‫‬‪⁪‫‎⁪​⁮‮ , String[] )
08:52:31    download    [!] An error occurred while downloading http://www.hentai-foundry.com/pictures/user/cherry-gig/886166/Bad-girls-like-it-Rough.: System.Net.WebException: Too many automatic redirections were attempted.
   at ‍‭‮⁫‮⁭⁫⁮⁮‭‮‪⁭⁭‌⁭​⁪‫‏‪⁪‍‪​⁪‪‪⁭⁫⁮‏‪⁯⁪‎⁭⁬‫⁯‮.‎⁪​‌⁯‌⁭⁯‮‪​‬‬‌⁪⁭⁪⁪‪‮⁮‬‮‪⁫⁬⁮⁬⁪⁫‪⁪⁯‮⁫⁯‫⁪‏‍‮(String , CookieContainer , String[] , String , ‮⁯‌⁪⁪⁫‪‏⁬​‏‪‫‭‏⁪‍‮‬⁭‫‪⁮‪⁫‌‭‌‍‭‌‫‬‪⁪‫‎⁪​⁮‮ , String[] )
   at ‌‭​‎⁭‭⁮‏⁪‮‌‎‌‪‏⁮⁪⁭‮⁪⁯⁭⁫‌⁬‬⁬‮‫‏⁭⁮‬‮⁬‭⁬‫‍⁫‮.‪⁭​⁪‌⁮‭⁮‭⁬‮⁮‬⁮⁪‮⁪⁮‫‮⁯⁭‬⁮⁬‬‭⁯⁬⁪⁭‏⁬​‫‭⁪⁬⁮‬‮(String& )
   at ⁯⁫​⁮⁯​‏⁭⁮⁯‍‫‏‮​‪‮‬‫‬‏⁫‍⁭‏​⁫‎‎‎⁫‎⁬‌‍‫⁮‭⁮⁪‮.‎⁯‬⁪⁯⁮‪⁮‎​⁫‎‪‫⁯‫‎‪‮‬⁫‎⁪​‮‭⁭‫‌‮⁭⁬‫‍⁪‪‬‮‫‎‮(‫‏​‫⁫‮⁪⁯‍‭⁫‌⁪​​‏‬⁪‮​⁭⁭⁮⁪⁯⁫⁭⁯‎⁭‪‏‏‍⁫‭⁫⁬⁮⁪‮ , String , ‌⁫​‭‏‎‮‌⁮⁫​‪‭⁮‪⁭‮⁮⁯‫⁫⁫‏‌⁮⁬​‪⁭⁯‌‎‭⁭‍‪⁭‎⁮⁬‮ )
08:52:31    http        [x] Exception was thrown when accessing http://www.hentai-foundry.com/pictures/user/cherry-gig/886166/Bad-girls-like-it-Rough.: System.Net.WebException: Too many automatic redirections were attempted.
   at System.Net.HttpWebRequest.GetResponse()
   at ‍‭‮⁫‮⁭⁫⁮⁮‭‮‪⁭⁭‌⁭​⁪‫‏‪⁪‍‪​⁪‪‪⁭⁫⁮‏‪⁯⁪‎⁭⁬‫⁯‮.‎⁪​‌⁯‌⁭⁯‮‪​‬‬‌⁪⁭⁪⁪‪‮⁮‬‮‪⁫⁬⁮⁬⁪⁫‪⁪⁯‮⁫⁯‫⁪‏‍‮(String , CookieContainer , String[] , String , ‮⁯‌⁪⁪⁫‪‏⁬​‏‪‫‭‏⁪‍‮‬⁭‫‪⁮‪⁫‌‭‌‍‭‌‫‬‪⁪‫‎⁪​⁮‮ , String[] )
08:52:31    download    [!] An error occurred while downloading http://www.hentai-foundry.com/pictures/user/cherry-gig/886166/Bad-girls-like-it-Rough.: System.Net.WebException: Too many automatic redirections were attempted.
   at ‍‭‮⁫‮⁭⁫⁮⁮‭‮‪⁭⁭‌⁭​⁪‫‏‪⁪‍‪​⁪‪‪⁭⁫⁮‏‪⁯⁪‎⁭⁬‫⁯‮.‎⁪​‌⁯‌⁭⁯‮‪​‬‬‌⁪⁭⁪⁪‪‮⁮‬‮‪⁫⁬⁮⁬⁪⁫‪⁪⁯‮⁫⁯‫⁪‏‍‮(String , CookieContainer , String[] , String , ‮⁯‌⁪⁪⁫‪‏⁬​‏‪‫‭‏⁪‍‮‬⁭‫‪⁮‪⁫‌‭‌‍‭‌‫‬‪⁪‫‎⁪​⁮‮ , String[] )
   at ‌‭​‎⁭‭⁮‏⁪‮‌‎‌‪‏⁮⁪⁭‮⁪⁯⁭⁫‌⁬‬⁬‮‫‏⁭⁮‬‮⁬‭⁬‫‍⁫‮.‪⁭​⁪‌⁮‭⁮‭⁬‮⁮‬⁮⁪‮⁪⁮‫‮⁯⁭‬⁮⁬‬‭⁯⁬⁪⁭‏⁬​‫‭⁪⁬⁮‬‮(String& )
   at ⁯⁫​⁮⁯​‏⁭⁮⁯‍‫‏‮​‪‮‬‫‬‏⁫‍⁭‏​⁫‎‎‎⁫‎⁬‌‍‫⁮‭⁮⁪‮.‎⁯‬⁪⁯⁮‪⁮‎​⁫‎‪‫⁯‫‎‪‮‬⁫‎⁪​‮‭⁭‫‌‮⁭⁬‫‍⁪‪‬‮‫‎‮(‫‏​‫⁫‮⁪⁯‍‭⁫‌⁪​​‏‬⁪‮​⁭⁭⁮⁪⁯⁫⁭⁯‎⁭‪‏‏‍⁫‭⁫⁬⁮⁪‮ , String , ‌⁫​‭‏‎‮‌⁮⁫​‪‭⁮‪⁭‮⁮⁯‫⁫⁫‏‌⁮⁬​‪⁭⁯‌‎‭⁭‍‪⁭‎⁮⁬‮ )
08:52:31    http        [x] Exception was thrown when accessing http://www.hentai-foundry.com/pictures/user/cherry-gig/886166/Bad-girls-like-it-Rough.: System.Net.WebException: Too many automatic redirections were attempted.
   at System.Net.HttpWebRequest.GetResponse()
   at ‍‭‮⁫‮⁭⁫⁮⁮‭‮‪⁭⁭‌⁭​⁪‫‏‪⁪‍‪​⁪‪‪⁭⁫⁮‏‪⁯⁪‎⁭⁬‫⁯‮.‎⁪​‌⁯‌⁭⁯‮‪​‬‬‌⁪⁭⁪⁪‪‮⁮‬‮‪⁫⁬⁮⁬⁪⁫‪⁪⁯‮⁫⁯‫⁪‏‍‮(String , CookieContainer , String[] , String , ‮⁯‌⁪⁪⁫‪‏⁬​‏‪‫‭‏⁪‍‮‬⁭‫‪⁮‪⁫‌‭‌‍‭‌‫‬‪⁪‫‎⁪​⁮‮ , String[] )
08:52:31    download    [!] An error occurred while downloading http://www.hentai-foundry.com/pictures/user/cherry-gig/886166/Bad-girls-like-it-Rough.: System.Net.WebException: Too many automatic redirections were attempted.
   at ‍‭‮⁫‮⁭⁫⁮⁮‭‮‪⁭⁭‌⁭​⁪‫‏‪⁪‍‪​⁪‪‪⁭⁫⁮‏‪⁯⁪‎⁭⁬‫⁯‮.‎⁪​‌⁯‌⁭⁯‮‪​‬‬‌⁪⁭⁪⁪‪‮⁮‬‮‪⁫⁬⁮⁬⁪⁫‪⁪⁯‮⁫⁯‫⁪‏‍‮(String , CookieContainer , String[] , String , ‮⁯‌⁪⁪⁫‪‏⁬​‏‪‫‭‏⁪‍‮‬⁭‫‪⁮‪⁫‌‭‌‍‭‌‫‬‪⁪‫‎⁪​⁮‮ , String[] )
   at ‌‭​‎⁭‭⁮‏⁪‮‌‎‌‪‏⁮⁪⁭‮⁪⁯⁭⁫‌⁬‬⁬‮‫‏⁭⁮‬‮⁬‭⁬‫‍⁫‮.‪⁭​⁪‌⁮‭⁮‭⁬‮⁮‬⁮⁪‮⁪⁮‫‮⁯⁭‬⁮⁬‬‭⁯⁬⁪⁭‏⁬​‫‭⁪⁬⁮‬‮(String& )
   at ⁯⁫​⁮⁯​‏⁭⁮⁯‍‫‏‮​‪‮‬‫‬‏⁫‍⁭‏​⁫‎‎‎⁫‎⁬‌‍‫⁮‭⁮⁪‮.‎⁯‬⁪⁯⁮‪⁮‎​⁫‎‪‫⁯‫‎‪‮‬⁫‎⁪​‮‭⁭‫‌‮⁭⁬‫‍⁪‪‬‮‫‎‮(‫‏​‫⁫‮⁪⁯‍‭⁫‌⁪​​‏‬⁪‮​⁭⁭⁮⁪⁯⁫⁭⁯‎⁭‪‏‏‍⁫‭⁫⁬⁮⁪‮ , String , ‌⁫​‭‏‎‮‌⁮⁫​‪‭⁮‪⁭‮⁮⁯‫⁫⁫‏‌⁮⁬​‪⁭⁯‌‎‭⁭‍‪⁭‎⁮⁬‮ )
08:52:31    task        [x] Failed to download image http://www.hentai-foundry.com/pictures/user/cherry-gig/886166/Bad-girls-like-it-Rough.
```
This link was added to downloads when i checked for new chapters(i have the artist page bookmarked) if it makes any difference

My guess would be that the dot in the end of image title might be causing this
When i try to download it using browser (i just drag'n'drop the image into folder) it produces file named "cherry-gig-886166-Bad_girls_like_it_Rough..jpg" two dots before extension.

**Comment by user3430534** [comment]
[Another example same case](https://www.hentai-foundry.com/pictures/user/aromasensei/886532/The-inspection-Part-1.)
08:01:47    http        [x] Exception was thrown when accessing http://www.hentai-foundry.com/pictures/user/aromasensei/886532/The-inspection-Part-1.: System.Net.WebException: Too many automatic redirections were attempted.
   at System.Net.HttpWebRequest.GetResponse()
   at ‍‭‮⁫‮⁭⁫⁮⁮‭‮‪⁭⁭‌⁭​⁪‫‏‪⁪‍‪​⁪‪‪⁭⁫⁮‏‪⁯⁪‎⁭⁬‫⁯‮.‎⁪​‌⁯‌⁭⁯‮‪​‬‬‌⁪⁭⁪⁪‪‮⁮‬‮‪⁫⁬⁮⁬⁪⁫‪⁪⁯‮⁫⁯‫⁪‏‍‮(String , CookieContainer , String[] , String , ‮⁯‌⁪⁪⁫‪‏⁬​‏‪‫‭‏⁪‍‮‬⁭‫‪⁮‪⁫‌‭‌‍‭‌‫‬‪⁪‫‎⁪​⁮‮ , String[] )
